"""
timesheet_app.py

Complete timesheet chatbot app using:
- Ollama (LLaMA 3.2 1B) for parsing user messages into structured timesheet data.
- Gradio for chat UI.
- SQL Server (pyodbc) OR Oracle (cx_Oracle or pyodbc/DSN) for persistence.

Requirements:
pip install gradio pyodbc requests python-dateutil

Optional (for Oracle):
pip install cx_Oracle
You may need Oracle Instant Client / proper DSN.

Environment variables (recommended):
OLLAMA_URL - base URL for local Ollama server (default http://localhost:11434)
OLLAMA_MODEL - model name (default llama3.2:1b or llama3.2-1b depending on your instance)
SQLSERVER_CONN - full pyodbc connection string for SQL Server (if using SQL Server)
ORACLE_DSN - DSN name or cx_Oracle connection string (if using Oracle)
DB_USER, DB_PASS - DB credentials if not included in connection string

How it works:
1. User types free-text (e.g., "Book 4 hours in Mars system on 26-10-2025 for Project 111111 on Task Code Review")
2. App calls Ollama to convert to structured JSON.
3. Shows draft in chat; user confirms to submit; entry inserted to DB.
4. Option to view recent timesheets.
"""

import os
import json
import re
import traceback
from datetime import datetime, date
from dateutil import parser as dateparser
import getpass
import sqlite3  # local fallback
import threading

import gradio as gr
import requests

# Try optional DB drivers
try:
    import pyodbc
except Exception:
    pyodbc = None

try:
    import cx_Oracle
except Exception:
    cx_Oracle = None

# ---------- Configuration ----------
OLLAMA_URL = os.getenv("OLLAMA_URL", "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.2:1b")  # may be "llama3.2-1b" in some installs
# DB config: fill one or both of these envvars (or change below)
SQLSERVER_CONN = os.getenv("SQLSERVER_CONN")  # e.g. "DRIVER={ODBC Driver 18 for SQL Server};SERVER=host;DATABASE=db;UID=user;PWD=pass"
ORACLE_DSN = os.getenv("ORACLE_DSN")  # e.g. "user/password@host:port/service" or use DSN configured in your system
# fallback: local sqlite (for quick testing) - file created in working dir
SQLITE_DB = os.path.join(os.path.dirname(__file__), "timesheet_local.db")

# Tables names
SQLSERVER_TABLE = "Timesheet_Mars"  # or Timesheet_Oracle depending on system
ORACLE_TABLE = "Timesheet_Oracle"

# Limit for fetch
RECENT_LIMIT = 10

# ---------- SQL table creation scripts ----------
SQLSERVER_CREATE = f"""
CREATE TABLE IF NOT EXISTS {SQLSERVER_TABLE} (
    id INT IDENTITY(1,1) PRIMARY KEY,
    username NVARCHAR(100),
    work_date DATE,
    hours FLOAT,
    system_name NVARCHAR(50),
    project NVARCHAR(200),
    task NVARCHAR(500),
    notes NVARCHAR(1000),
    created_at DATETIME DEFAULT GETDATE()
);
"""

ORACLE_CREATE = f"""
-- Oracle flavors differ; a simple example:
CREATE TABLE {ORACLE_TABLE} (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100),
    work_date DATE,
    hours NUMBER,
    system_name VARCHAR2(50),
    project VARCHAR2(200),
    task VARCHAR2(500),
    notes VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);
"""

SQLITE_CREATE = f"""
CREATE TABLE IF NOT EXISTS timesheets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT,
    work_date TEXT,
    hours REAL,
    system_name TEXT,
    project TEXT,
    task TEXT,
    notes TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
"""

# ---------- Helper functions ----------
def get_local_username():
    """Return the OS username to store in timesheet entries."""
    try:
        return getpass.getuser()
    except Exception:
        return "unknown_user"

# Ollama wrapper - attempt two common ways: 'ollama' HTTP /api/chat or /api/generate.
def call_ollama_chat(messages, model=OLLAMA_MODEL, timeout=15):
    """
    messages: list of {"role":"system"/"user"/"assistant", "content": "..."}
    Returns assistant text (string).
    """
    # Try /api/chat (chat endpoint)
    try:
        url = OLLAMA_URL.rstrip("/") + "/api/chat"
        payload = {"model": model, "messages": messages}
        resp = requests.post(url, json=payload, timeout=timeout)
        resp.raise_for_status()
        data = resp.json()
        # Ollama responses vary by version; try common keys
        if isinstance(data, dict) and "choices" in data and data["choices"]:
            # choose the assistant message
            text = data["choices"][0].get("message", {}).get("content") or data["choices"][0].get("content")
            if text:
                return text
        # some versions return {"id":...,"model":...,"output":[{"id":...,"content":"..."}]}
        if isinstance(data, dict) and "output" in data and data["output"]:
            return data["output"][0].get("content", "")
    except Exception:
        # fallback later
        pass

    # Try /api/generate
    try:
        url = OLLAMA_URL.rstrip("/") + "/api/generate"
        prompt = ""
        # build a flattened prompt from messages (chat->instruction-style)
        for m in messages:
            role = m.get("role", "user")
            prompt += f"[{role}]: {m.get('content','')}\n"
        payload = {"model": model, "prompt": prompt}
        resp = requests.post(url, json=payload, timeout=timeout)
        resp.raise_for_status()
        data = resp.json()
        if isinstance(data, dict):
            # some versions return {"choices":[{"content":"..."}]}
            if "choices" in data and data["choices"]:
                return data["choices"][0].get("content", "")
            if "output" in data and data["output"]:
                return data["output"][0].get("content", "")
    except Exception:
        pass

    raise RuntimeError("Failed to call Ollama. Check OLLAMA_URL and that the Ollama daemon is available.")

# Use LLM to parse user input into structured JSON (date, hours, system, project, task, notes)
PARSER_SYSTEM_PROMPT = """
You are a strict JSON-only parser. When given a user sentence describing a timesheet entry, output only valid JSON (no commentary, no markdown).
The JSON schema:
{
  "date": "YYYY-MM-DD" or null,
  "hours": float or null,
  "system": "Mars"|"Oracle"|other string or null,
  "project": string or null,
  "task": string or null,
  "notes": string or null
}
Rules:
- Parse dates in any reasonable format (26-10-2025, 26/10/2025, 2025-10-26, "today", "yesterday") and output ISO date YYYY-MM-DD. If date is absent, leave null.
- Parse hours as a number (can be integer or decimal). If not present, null.
- If user mentions "book/submit/add X hours", treat that as hours.
- Do not output anything but a single JSON object.
"""

def parse_text_to_structured(text):
    """Call the LLM to parse free text into JSON following the schema above."""
    messages = [
        {"role": "system", "content": PARSER_SYSTEM_PROMPT},
        {"role": "user", "content": text}
    ]
    raw = call_ollama_chat(messages)
    # The LLM should return JSON-only, but be defensive:
    # Extract first JSON object in response.
    try:
        json_text = raw.strip()
        # find the first { ... } block
        m = re.search(r"\{.*\}", json_text, flags=re.DOTALL)
        if m:
            json_text = m.group(0)
        data = json.loads(json_text)
    except Exception as e:
        # fallback heuristic parsing: naive regex
        data = fallback_parse(text)
    # Normalize fields
    # Parse date strings to YYYY-MM-DD if possible
    dt = data.get("date")
    if dt:
        try:
            parsed = dateparser.parse(str(dt), dayfirst=True)
            data["date"] = parsed.date().isoformat()
        except Exception:
            # attempt to interpret words
            lower = str(dt).lower()
            if lower in ("today",):
                data["date"] = date.today().isoformat()
            elif lower in ("yesterday",):
                data["date"] = (date.today() - timedelta(days=1)).isoformat()
            else:
                data["date"] = None
    else:
        data["date"] = None
    # Hours
    try:
        data["hours"] = float(data["hours"]) if data.get("hours") is not None else None
    except Exception:
        data["hours"] = None
    # Normalize system & text fields
    for k in ("system", "project", "task", "notes"):
        data[k] = data.get(k) if data.get(k) is not None else None
    return data

def fallback_parse(text):
    """Very small fallback parser if LLM fails - returns dict matching schema with many nulls."""
    out = {"date": None, "hours": None, "system": None, "project": None, "task": None, "notes": None}
    # hours: look for pattern like 'X hour(s)'
    m = re.search(r"(\d+(?:\.\d+)?)\s*(?:hours|hrs|hour|h)\b", text, flags=re.I)
    if m:
        out["hours"] = float(m.group(1))
    # date: simple dd-mm-yyyy or dd/mm/yyyy or yyyy-mm-dd
    m = re.search(r"(\d{1,2}[-/]\d{1,2}[-/]\d{2,4})", text)
    if m:
        try:
            parsed = dateparser.parse(m.group(1), dayfirst=True)
            out["date"] = parsed.date().isoformat()
        except Exception:
            out["date"] = None
    # system: look for 'mars' or 'oracle'
    if re.search(r"\bmars\b", text, flags=re.I):
        out["system"] = "Mars"
    elif re.search(r"\boracle\b", text, flags=re.I):
        out["system"] = "Oracle"
    # project: look for word Project or ProjectID
    m = re.search(r"(?:project|proj|p)\s*[#:]?\s*([A-Za-z0-9\-\_]+)", text, flags=re.I)
    if m:
        out["project"] = m.group(1)
    # task: take a trailing 'for' phrase
    m = re.search(r"for\s+(.*)", text, flags=re.I)
    if m:
        out["task"] = m.group(1).strip()
    # notes: none
    return out

# ---------- Database functions ----------
# We'll provide three DB backends: SQL Server via pyodbc, Oracle via cx_Oracle or pyodbc DSN, and fallback sqlite.

def ensure_sqlite():
    conn = sqlite3.connect(SQLITE_DB)
    cur = conn.cursor()
    cur.execute(SQLITE_CREATE)
    conn.commit()
    conn.close()

def insert_into_sqlite(entry):
    conn = sqlite3.connect(SQLITE_DB)
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO timesheets (username, work_date, hours, system_name, project, task, notes) VALUES (?, ?, ?, ?, ?, ?, ?)",
        (entry["username"], entry["date"], entry["hours"], entry["system"], entry["project"], entry["task"], entry.get("notes"))
    )
    conn.commit()
    conn.close()

def fetch_recent_sqlite(username, limit=RECENT_LIMIT):
    conn = sqlite3.connect(SQLITE_DB)
    cur = conn.cursor()
    cur.execute("SELECT work_date, hours, system_name, project, task, notes FROM timesheets WHERE username=? ORDER BY created_at DESC LIMIT ?",
                (username, limit))
    rows = cur.fetchall()
    conn.close()
    return rows

def ensure_sqlserver():
    if not pyodbc or not SQLSERVER_CONN:
        return False
    try:
        conn = pyodbc.connect(SQLSERVER_CONN, autocommit=True)
        cur = conn.cursor()
        # create table if not exists - Note: SQL Server requires a different check; we'll try create and ignore error if exists.
        try:
            cur.execute(SQLSERVER_CREATE)
        except Exception:
            # ignore - table may already exist
            pass
        conn.close()
        return True
    except Exception as e:
        print("SQL Server connection failed:", e)
        return False

def insert_sqlserver(entry):
    conn = pyodbc.connect(SQLSERVER_CONN)
    cur = conn.cursor()
    table = SQLSERVER_TABLE if entry["system"] and entry["system"].lower() == "mars" else SQLSERVER_TABLE
    query = f"INSERT INTO {table} (username, work_date, hours, system_name, project, task, notes) VALUES (?, ?, ?, ?, ?, ?, ?)"
    # convert date to date object if string
    work_date = entry["date"]
    try:
        if work_date:
            work_date = dateparser.parse(work_date).date()
    except Exception:
        work_date = None
    cur.execute(query, (entry["username"], work_date, entry["hours"], entry["system"], entry["project"], entry["task"], entry.get("notes")))
    conn.commit()
    conn.close()

def fetch_recent_sqlserver(username, limit=RECENT_LIMIT, system_hint=None):
    conn = pyodbc.connect(SQLSERVER_CONN)
    cur = conn.cursor()
    table = SQLSERVER_TABLE
    # SQL Server TOP
    query = f"SELECT TOP {limit} work_date, hours, system_name, project, task, notes FROM {table} WHERE username=? ORDER BY work_date DESC"
    cur.execute(query, (username,))
    rows = cur.fetchall()
    conn.close()
    return rows

def ensure_oracle():
    if not ORACLE_DSN:
        return False
    try:
        if cx_Oracle:
            # attempt to connect using cx_Oracle if DSN formatted as user/password@host...
            conn = cx_Oracle.connect(ORACLE_DSN)
            cur = conn.cursor()
            # create if needed - ignore errors
            try:
                cur.execute(ORACLE_CREATE)
            except Exception:
                pass
            conn.close()
            return True
        elif pyodbc:
            conn = pyodbc.connect(ORACLE_DSN)
            cur = conn.cursor()
            try:
                cur.execute(ORACLE_CREATE)
            except Exception:
                pass
            conn.close()
            return True
    except Exception as e:
        print("Oracle connection failed:", e)
        return False
    return False

def insert_oracle(entry):
    # Use cx_Oracle if available; else pyodbc
    work_date = entry["date"]
    try:
        if work_date:
            work_date = dateparser.parse(work_date).date()
    except Exception:
        work_date = None
    if cx_Oracle and isinstance(ORACLE_DSN, str) and "@" in ORACLE_DSN:
        conn = cx_Oracle.connect(ORACLE_DSN)
        cur = conn.cursor()
        query = f"INSERT INTO {ORACLE_TABLE} (username, work_date, hours, system_name, project, task, notes) VALUES (:1, :2, :3, :4, :5, :6, :7)"
        cur.execute(query, (entry["username"], work_date, entry["hours"], entry["system"], entry["project"], entry["task"], entry.get("notes")))
        conn.commit()
        conn.close()
    elif pyodbc and ORACLE_DSN:
        conn = pyodbc.connect(ORACLE_DSN)
        cur = conn.cursor()
        query = f"INSERT INTO {ORACLE_TABLE} (username, work_date, hours, system_name, project, task, notes) VALUES (?, ?, ?, ?, ?, ?, ?)"
        cur.execute(query, (entry["username"], work_date, entry["hours"], entry["system"], entry["project"], entry["task"], entry.get("notes")))
        conn.commit()
        conn.close()
    else:
        raise RuntimeError("No suitable Oracle driver/DSN available.")

def fetch_recent_oracle(username, limit=RECENT_LIMIT):
    # Basic implementation: using cx_Oracle or pyodbc
    if cx_Oracle and isinstance(ORACLE_DSN, str) and "@" in ORACLE_DSN:
        conn = cx_Oracle.connect(ORACLE_DSN)
        cur = conn.cursor()
        query = f"SELECT work_date, hours, system_name, project, task, notes FROM {ORACLE_TABLE} WHERE username=:1 ORDER BY work_date DESC FETCH NEXT :2 ROWS ONLY"
        cur.execute(query, (username, limit))
        rows = cur.fetchall()
        conn.close()
        return rows
    elif pyodbc and ORACLE_DSN:
        conn = pyodbc.connect(ORACLE_DSN)
        cur = conn.cursor()
        query = f"SELECT work_date, hours, system_name, project, task, notes FROM {ORACLE_TABLE} WHERE username=? ORDER BY work_date DESC"
        cur.execute(query, (username,))
        rows = cur.fetchmany(limit)
        conn.close()
        return rows
    else:
        return []

# Higher-level wrapper
def submit_timesheet_to_backend(entry):
    """
    Try to submit to DB in this priority:
    1) If system is 'Oracle' -> attempt Oracle insert
    2) Else attempt SQL Server insert
    3) Else fallback to sqlite local
    """
    # ensure sqlite exists
    ensure_sqlite()

    system_hint = (entry.get("system") or "").lower() if entry.get("system") else ""

    # If user explicitly chose Oracle
    if system_hint == "oracle" and ORACLE_DSN:
        try:
            ensure_oracle()
            insert_oracle(entry)
            return {"ok": True, "backend": "oracle"}
        except Exception as e:
            print("Oracle insert failed:", e)
            # fallback to other
    # Try SQL Server if configured
    if SQLSERVER_CONN and pyodbc:
        try:
            ensure_sqlserver()
            insert_sqlserver(entry)
            return {"ok": True, "backend": "sqlserver"}
        except Exception as e:
            print("SQL Server insert failed:", e)
    # Fallback: local sqlite
    try:
        insert_into_sqlite(entry)
        return {"ok": True, "backend": "sqlite"}
    except Exception as e:
        traceback.print_exc()
        return {"ok": False, "error": str(e)}

def get_recent_timesheets(username, preferred_system=None, limit=RECENT_LIMIT):
    """Fetch recent timesheets; try DB backends and return list of rows."""
    # prefer sqlite always available
    ensure_sqlite()
    rows = []
    # try SQL Server
    if SQLSERVER_CONN and pyodbc:
        try:
            rows = fetch_recent_sqlserver(username, limit)
            # normalize pyodbc row objects to tuples
            rows = [tuple(r) for r in rows]
            if rows:
                return rows
        except Exception:
            pass
    # try Oracle
    if ORACLE_DSN:
        try:
            rows = fetch_recent_oracle(username, limit)
            rows = [tuple(r) for r in rows]
            if rows:
                return rows
        except Exception:
            pass
    # fallback sqlite
    try:
        rows = fetch_recent_sqlite(username, limit)
        return rows
    except Exception:
        return []

# ---------- Gradio Chat App ----------
DEFAULT_PROMPT = "Hi — tell me the timesheet entry you'd like to record (e.g., 'Book 4 hours in Mars on 26-10-2025 for Project 111111 on Task Code Review')"

def format_draft(entry):
    lines = [
        "Draft timesheet entry:",
        f"- Username: {entry['username']}",
        f"- Date: {entry.get('date') or 'NOT PROVIDED'}",
        f"- Hours: {entry.get('hours') or 'NOT PROVIDED'}",
        f"- System: {entry.get('system') or 'NOT PROVIDED'}",
        f"- Project: {entry.get('project') or 'NOT PROVIDED'}",
        f"- Task: {entry.get('task') or 'NOT PROVIDED'}",
    ]
    if entry.get("notes"):
        lines.append(f"- Notes: {entry.get('notes')}")
    lines.append("\nPlease **Confirm** to submit or **Edit** your message to change.")
    return "\n".join(lines)

def render_timesheet_rows(rows):
    if not rows:
        return "No recent timesheets found."
    lines = []
    for r in rows:
        # r expected: (work_date, hours, system_name, project, task, notes)
        wd = r[0]
        if isinstance(wd, (datetime, date)):
            wd = wd.isoformat()
        lines.append(f"{wd} | {r[1]}h | {r[2]} | {r[3]} | {r[4]}{(' | ' + str(r[5])) if r[5] else ''}")
    return "\n".join(lines)

# State structure: { "pending": dict or None, "history": [(user, bot), ...] }
def handle_user_message(message, state):
    state = state or {"pending": None, "history": []}
    username = get_local_username()
    user_msg = message.strip()
    # First, if there is a pending draft (awaiting confirm), interpret "confirm" or "yes" or "submit" as confirmation
    if state.get("pending"):
        lower = user_msg.lower()
        if lower in ("yes", "y", "confirm", "submit", "s", "ok", "okay"):
            # Submit
            entry = state["pending"]
            entry["username"] = username
            res = submit_timesheet_to_backend(entry)
            if res.get("ok"):
                bot_msg = f"✅ Timesheet submitted to backend: {res.get('backend')}. Do you want to view recent timesheets? (yes/no)"
            else:
                bot_msg = f"⚠️ Failed to submit timesheet: {res.get('error')}. Try editing and resubmitting."
            state["history"].append((user_msg, bot_msg))
            state["pending"] = None
            return state, state["history"]
        elif lower in ("no", "n", "cancel", "edit"):
            # Cancel or edit: clear pending and prompt user to rephrase
            bot_msg = "Draft canceled. Please edit your message or provide a new timesheet entry."
            state["history"].append((user_msg, bot_msg))
            state["pending"] = None
            return state, state["history"]
        elif lower.startswith("show") or "recent" in lower or "view" in lower:
            # User asks to view timesheets instead of confirming
            rows = get_recent_timesheets(username)
            bot_msg = "📋 Recent timesheets:\n" + render_timesheet_rows(rows)
            state["history"].append((user_msg, bot_msg))
            # keep pending draft until user explicitly confirms or cancels
            return state, state["history"]
        else:
            # User provided an edit/new message while pending: re-parse new message
            try:
                parsed = parse_text_to_structured(user_msg)
                parsed["username"] = username
                # if parsed fields are mostly null, keep some values from previous pending (helpful)
                old = state["pending"]
                for k in ("date", "hours", "system", "project", "task", "notes"):
                    if not parsed.get(k) and old.get(k):
                        parsed[k] = old.get(k)
                state["pending"] = parsed
                bot_msg = format_draft(parsed)
                state["history"].append((user_msg, bot_msg))
                return state, state["history"]
            except Exception as e:
                state["history"].append((user_msg, f"Parsing error: {e}"))
                return state, state["history"]
    # No pending draft: parse message to create one
    try:
        parsed = parse_text_to_structured(user_msg)
        parsed["username"] = username
        # If parsed all nulls, ask user to rephrase
        if not any([parsed.get("date"), parsed.get("hours"), parsed.get("project"), parsed.get("task"), parsed.get("system")]):
            bot_msg = "I couldn't extract a timesheet from that. Please include at least hours and project/task (e.g., 'Book 4 hours in Mars on 26-10-2025 for Project 111111 on Task Code Review')."
            state["history"].append((user_msg, bot_msg))
            return state, state["history"]
        # Create draft
        state["pending"] = parsed
        bot_msg = format_draft(parsed)
        state["history"].append((user_msg, bot_msg))
        return state, state["history"]
    except Exception as e:
        tb = traceback.format_exc()
        bot_msg = "Error parsing request. " + str(e)
        state["history"].append((user_msg, bot_msg))
        return state, state["history"]

# Build Gradio interface
def build_app():
    ensure_sqlite()
    # try to ensure other DBs if possible (non-blocking)
    t = threading.Thread(target=lambda: (ensure_sqlserver(), ensure_oracle()), daemon=True)
    t.start()

    with gr.Blocks(title="Timesheet Chatbot (Ollama + DB)") as demo:
        gr.Markdown("## Timesheet Chatbot\nType natural language to add a timesheet (e.g. 'Book 4 hours in Mars on 26-10-2025 for Project 111111 on Task Code Review'). Confirm the draft to submit.")
        chatbot = gr.Chatbot()
        state = gr.State({"pending": None, "history": []})
        msg = gr.Textbox(placeholder=DEFAULT_PROMPT)
        with gr.Row():
            submit_btn = gr.Button("Send")
            confirm_btn = gr.Button("Confirm (if draft shown)")
            view_btn = gr.Button("View recent timesheets")
            clear_btn = gr.Button("Clear history")

        def on_send(text, state):
            if not text or not text.strip():
                return gr.update(value=""), state, chatbot
            state, history = handle_user_message(text, state)
            # render chat history in chatbot component
            chat_messages = [(u, a) for (u, a) in history]
            return "", state, chat_messages

        def on_confirm(_, state):
            # simulate user saying "confirm"
            state, history = handle_user_message("confirm", state)
            chat_messages = [(u, a) for (u, a) in history]
            return state, chat_messages

        def on_view(_, state):
            state, history = handle_user_message("show recent timesheets", state)
            chat_messages = [(u, a) for (u, a) in history]
            return state, chat_messages

        def on_clear(_, state):
            state = {"pending": None, "history": []}
            return state, []

        submit_btn.click(on_send, [msg, state], [msg, state, chatbot])
        msg.submit(on_send, [msg, state], [msg, state, chatbot])
        confirm_btn.click(on_confirm, [msg, state], [state, chatbot])
        view_btn.click(on_view, [msg, state], [state, chatbot])
        clear_btn.click(on_clear, [msg, state], [state, chatbot])

    return demo

if __name__ == "__main__":
    app = build_app()
    app.launch(server_name="0.0.0.0", server_port=7860, share=False)
